In [4]:
size = input().split()
m = int(size[0])
n = int(size[1])
l = []

for i in range(m):
    row = [int(i) for i in input().split()]
    l.append(row)
l



5 2
2 3
5 4
6 1
8 2
3 6


[[2, 3], [5, 4], [6, 1], [8, 2], [3, 6]]

In [9]:
area = []
for i in range(m):
    area.append(l[i][0]*l[i][1])
area

[6, 20, 6, 16, 18]

In [17]:
min_ = max(area)
first = 0
second = 0

for i in range(m):
    for j in range(m):
        if min_ > abs(area[i]-area[j]) and i!=j:
            min_ = abs(area[i]-area[j])
            first = i
            second = j
print(l[first],l[second])
        
        
        

[2, 3] [6, 1]


In [22]:
def subArrayExists(arr, n):
    # traverse through array
    # and store prefix sums
    n_sum = 0
    s = set()
 
    for i in range(n):
        n_sum += arr[i]
 
        # If prefix sum is 0 or
        # it is already present
        if n_sum == 0 or n_sum in s:
            return True
        s.add(n_sum)
        print(s)
 
    return False
 

# Driver code
arr = [2, 1, -3,4]
n = len(arr)
if subArrayExists(arr, n) == True:
    print("Found a sunbarray with 0 sum")
else:
    print("No Such sub array exits!")

{2}
{2, 3}
Found a sunbarray with 0 sum


In [3]:
import numpy as np

In [5]:
np.ones((3,4),dtype =int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [9]:
np.empty((4,4),dtype = int)

array([[94645353855568,              0,   489626271861,   433791696995],
       [  498216206368,   468151435365,   476741369968,   416611827826],
       [  450971566194,   519691042924,   502511173664,   416611827822],
       [  416611827830,   463856468073,   420906795105,   433791697004]])

In [10]:
l = [[1,2,3],[3,4,5]]


In [13]:
narr =  np.array(l)
narr

array([[1, 2, 3],
       [3, 4, 5]])

In [15]:
nzero = np.zeros(10,dtype = int)
nzero[4] = 1
nzero

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

In [17]:
a = np.array([0,1,2,3])
a.shape


(4,)

In [22]:
a = np.arange(9,49)
a

array([ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25,
       26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42,
       43, 44, 45, 46, 47, 48])

In [25]:
a  = np.linspace(9,49,dtype = int)

In [26]:
a


array([ 9,  9, 10, 11, 12, 13, 13, 14, 15, 16, 17, 17, 18, 19, 20, 21, 22,
       22, 23, 24, 25, 26, 26, 27, 28, 29, 30, 31, 31, 32, 33, 34, 35, 35,
       36, 37, 38, 39, 40, 40, 41, 42, 43, 44, 44, 45, 46, 47, 48, 49])

In [30]:
a = np.eye(5,6)
a

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.]])

In [34]:
a = np.linspace(1,5,num = 9)
a

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [35]:
l = [1,2,0,0,4,0]


In [36]:
arr = np.array(l)

In [41]:
print(np.where(arr!=0))

(array([0, 1, 4]),)


In [42]:
arr = np.arange(1,20,2)
arr

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [43]:
print(np.where(arr%3==0))

(array([1, 4, 7]),)


In [46]:
arr = np.arange(1,11,1)

indx_arr = np.where(arr%2==1)
    
indx_arr

(array([0, 2, 4, 6, 8]),)

In [47]:
for i in indx_arr:
    arr[i] = -1
arr

array([-1,  2, -1,  4, -1,  6, -1,  8, -1, 10])

In [76]:
l = [1,21,133,4,115,133,27,8,27]


In [77]:
arr = np.array(l)

In [78]:
arr[arr.argmax()] = 0
arr

array([  1,  21,   0,   4, 115, 133,  27,   8,  27])

In [79]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [93]:
arr_bool = arr[(arr<3) | (arr>8)]
arr_bool

array([ 1,  2,  9, 10])

In [101]:
age = np.arange(1,21)

In [104]:
height = np.random.randint(30,155,20)

In [108]:
height


array([136,  80, 154, 150,  35,  92,  33, 106,  30, 144, 140,  97,  50,
        38,  88,  78, 127, 112, 117,  81,  71])

In [111]:
height_bool = np.where(height>100)

In [114]:
print(age[height_bool])

[ 1  3  4  8 10 11 17 18 19]


In [122]:
arr = np.arange(21,1,-1)

NameError: name 'shape' is not defined

In [125]:
arr

array([[21, 20, 19, 18, 17],
       [16, 15, 14, 13, 12],
       [11, 10,  9,  8,  7],
       [ 6,  5,  4,  3,  2]])

In [132]:
bool_arr = arr[arr[:,2].argsort()]

In [133]:
bool_arr

array([[ 6,  5,  4,  3,  2],
       [11, 10,  9,  8,  7],
       [16, 15, 14, 13, 12],
       [21, 20, 19, 18, 17]])